In [79]:
import shap
import explanations
import numpy as np
import pandas as pd

from sklearn.model_selection import train_test_split
from sklearn.ensemble import RandomForestRegressor

from utils import feature_names
import time

In [80]:

def generate_data(n): 
    x_1 = np.random.normal(0, 2, size=(n))
    x_2 = np.random.normal(0, 2, size=(n))
    x_3 = np.random.normal(0, 2, size=(n))
    x_4 = x_2
    x_5 = x_1
    y = (2 * x_1) + (3 * x_2) + x_3
    X = pd.DataFrame()
    X['X_1']= x_1
    X['X_2'] = x_2
    X['X_3']= x_3
    X['X_4']= x_4
    X['X_5'] = x_5
    return X,y

In [81]:
X, y = generate_data(1000)

In [82]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.20, random_state=42)
model = RandomForestRegressor(max_depth=100, random_state=42)
model.fit(X_train, y_train)
model.score(X_test,y_test)

0.9766868445344037

In [83]:
st = time.time()
explanation_app = explanations.model_explanations(X_test,y_test,model,output='text')
et = time.time()
print(et-st)

"""if __name__ == '__main__':
    explanation_app.run_server(debug=True)"""
print(explanation_app)
torty_orders = list(explanation_app.index)

0.02360391616821289
  Feature  Importance
1     X_2     1.48565
3     X_4     1.48565
2     X_3     0.79247
0     X_1     0.68710
4     X_5     0.68710


In [84]:
st = time.time()
explainer = shap.Explainer(model, X_test)
shap_values = explainer(X_test,check_additivity=False)
et = time.time()
print(et-st)

2.5548181533813477


In [85]:
attributions = shap_values.values.mean(axis=0)
attributions = attributions.reshape(X_test.shape[1])
feature_names(X_test,attributions)


Feature  Importance
3     X_4     0.17762
1     X_2     0.16393
2     X_3     0.10122
0     X_1     0.05770
4     X_5     0.05754

In [88]:
overall_attributions = []
for i in range(0,100):
    explainer = shap.Explainer(model, X_test[0:10])
    shap_values = explainer(X_test[0:10],check_additivity=False)
    attributions = shap_values.values.mean(axis=0)
    attributions = attributions.reshape(X_test.shape[1])
    overall_attributions.append(attributions)
    
 
    

In [89]:
overall_attributions

[array([ 3.33066907e-17,  0.00000000e+00, -2.77555756e-18,  0.00000000e+00,
        -4.44089210e-17]),
 array([ 3.33066907e-17,  0.00000000e+00, -2.77555756e-18,  0.00000000e+00,
        -4.44089210e-17]),
 array([ 3.33066907e-17,  0.00000000e+00, -2.77555756e-18,  0.00000000e+00,
        -4.44089210e-17]),
 array([ 3.33066907e-17,  0.00000000e+00, -2.77555756e-18,  0.00000000e+00,
        -4.44089210e-17]),
 array([ 3.33066907e-17,  0.00000000e+00, -2.77555756e-18,  0.00000000e+00,
        -4.44089210e-17]),
 array([ 3.33066907e-17,  0.00000000e+00, -2.77555756e-18,  0.00000000e+00,
        -4.44089210e-17]),
 array([ 3.33066907e-17,  0.00000000e+00, -2.77555756e-18,  0.00000000e+00,
        -4.44089210e-17]),
 array([ 3.33066907e-17,  0.00000000e+00, -2.77555756e-18,  0.00000000e+00,
        -4.44089210e-17]),
 array([ 3.33066907e-17,  0.00000000e+00, -2.77555756e-18,  0.00000000e+00,
        -4.44089210e-17]),
 array([ 3.33066907e-17,  0.00000000e+00, -2.77555756e-18,  0.00000000e+0